"use client"

import useSWR from "swr"
import { Bell, Check, CheckCheck } from "lucide-react"

import { PageHeader } from "@/components/page-header"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { apiFetch, unpackResults } from "@/lib/api"
import { formatDate } from "@/lib/format"
import type { Paginated } from "@/lib/types"
import { cn } from "@/lib/utils"

type Notification = { id: number; title: string; message: string; is_read: boolean; created_at: string }

export default function NotificationsPage() {
  const { data, isLoading, mutate } = useSWR<Paginated<Notification> | Notification[]>("notifications/", apiFetch)
  const notifications = unpackResults(data)

  async function markRead(item: Notification) {
    await apiFetch(`notifications/${item.id}/`, { method: "PATCH", body: JSON.stringify({ is_read: true }) })
    mutate()
  }

  async function markAllRead() {
    await Promise.all(notifications.filter((item) => !item.is_read).map(markRead))
  }

  return <><PageHeader eyebrow="Inbox" title="Notifications" description="Updates and alerts generated by inventory activity." actions={<Button variant="outline" onClick={markAllRead} disabled={!notifications.some((item) => !item.is_read)}><CheckCheck />Mark all read</Button>} /><Card className="overflow-hidden border-border/70 shadow-sm"><CardContent className="p-0">{isLoading ? <div className="space-y-3 p-5">{Array.from({ length: 5 }).map((_, index) => <Skeleton className="h-20" key={index} />)}</div> : notifications.length ? <div className="divide-y">{notifications.map((item) => <div key={item.id} className={cn("flex gap-4 p-5", !item.is_read && "bg-primary/[0.035]")}><span className={cn("mt-0.5 grid size-9 shrink-0 place-items-center rounded-full", item.is_read ? "bg-muted text-muted-foreground" : "bg-primary/10 text-primary")}><Bell className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className={cn("text-sm", !item.is_read && "font-semibold")}>{item.title}</p><span className="font-mono text-[11px] text-muted-foreground">{formatDate(item.created_at, true)}</span></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.message}</p></div>{!item.is_read && <Button variant="ghost" size="icon-sm" onClick={() => markRead(item)} aria-label="Mark as read"><Check /></Button>}</div>)}</div> : <div className="p-16 text-center"><Bell className="mx-auto size-8 text-muted-foreground/50" /><p className="mt-4 font-medium">You’re all caught up</p><p className="mt-1 text-sm text-muted-foreground">New alerts will appear here.</p></div>}</CardContent></Card></>
}

